package huolala;

import java.time.Duration;
import java.time.Instant;

public class ForLoopCalculator implements Calculator {

    public static final String str = "apppaaccaadwqelqrewtsabzbbjnkolxohushadsadafdcndlasnlcccccdsmlkmytryulktyiuy" +
            "kolxvfdytmhkoujmgerfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplvfdvvewefdswqvfvmmoofdslkw" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecssfsdlkkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncnkolxodna" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewqnlllljnkolxohushadsadafdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluufdsororppwponzdjnkccccadsadhtrhmklvdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "jdshddsayddulksfifjejdsnfmvjyujyldsnluuueeofdsororpbgfbpwponzdjadsadafdsdbgfvsljpoplewewqvfvmmofvdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtokcretrhuyiubgfblmxkjcvfsferjyuydfgudewioilfbbsdfsvuiolmkolisjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsknmewbhhipoxzbgfnljnkolxohrfenmuishadsadhnhtrfshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfdafdsmmoofdslkwecfefsklhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlugtreofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewqnlljnkolxohushadsadafdsmmoofdslkwecfefskluhghhfddsk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlurgueeofdsororppwponzdjnkgfdgdsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfdafdsmmoofdslkwecfefsklhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlugtreofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewqnlljnkolxohushadsadafdsmmoofdslkwecfefskluhghhfddsk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlurgueeofdsororppwponzdjndgdsadafdsdfewvsljpoplewefdswqvfvmmoofdslkw" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmokpefoplewefdswqljdyabpppojvdnnccwfwpekorio" +
            "pytupewijewnrfmkslmdsdfkkloejtoirejtckcretrhuyiugmlmvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiwmrbgfvfdvlskjjvvnsdsfpoiroppyrutrpczc" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafgtrgyoofdslkwfdoinoicxzncjnkolxohusdn" +
            "ecxoqwqjdasjfffksxbjnfrelxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmglofdslkwfdoinoicxzncjnkolxousdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsmmoofnjlsczxfmekmfreklmfklegmkoiprewmrvlsskkkjjvvnsdnflsfpoiroppyrutrpczmc" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjvfdklmljpoplewefdswqljabpojvdnnccwcvdomwekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsmmoofnjlsczxfmekmfreklmfklegmkoiprewmrvlsskkkjjvvnsdnflsfpoiroppyrutrpczmc" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjvfdklmljpoplewefdswqljabpojvdnnccwcvdomwekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpdsfecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcompekor" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtwfwckcretrhuyvbgflmxcverjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewregelqnlllljnkolxohushadsadafdsmmoofdslkweckluhghhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlytljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkcccbgfcafewfdsdvsljoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpechgfkjckjdsmwprwjklmljpoplewefdswqljdfdsabpojvdnnccwomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvslfdsophgefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjjgtqqtggxkmjhdjvvffvkmpecdskjckjdsmwprwjklmljpoplebffdswqljdyabpppojvdncdsncwcomwpeorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioifrlfbbsdfsvxvynuynfsjnvvnreg" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsmmoofnjlsczxfmekmfreklmfklegmkoiprewmrvlsskkkjjvvnsdnflsfpoiroppyrutrpczmc" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpopwefrfdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlljnkolxohedushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpopwefrfdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlljnkolxohedushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpopwefrfdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlljnkolxohedushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpopwefrfdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlljnkolxohedushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlugtreofdsororppwponzdjnkccadsadvfafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewvfdefdswqljdyabpppojvdnnbomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewqnlljnkolxohushadsadafdsmmoofdslkwecfefskluhghhfddsk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlurgueeofdsororppwponzdjnkgfdgdsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkuymadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsmmoofnjlsczxfmekmfreklmfklegmkoiprewmrvlsskkkjjvvnsdnflsfpoiroppyrutrpczmc" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjvfdklmljpoplewefdswqljabpojvdnnccwcvdomwekorio" +
            "pytupewijewnrfmkslmdsdfkklrhuyiummxcvfsferjyumjhnvfdveydfguioilgfddfbbsdfferfrejymtsvxccvfsynfsnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlugtreofdsororppwponzdjnkccadsadvfafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewvfdefdswqljdyabpppojvdnnbomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewqnlljnkolxohushadsadafdsmmoofdslkwecfefskluhghhfddsk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpopwefrfdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlljnkolxohedushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlugtreofdsororppwponzdjnkccadsadvfafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewvfdefdswqljdyabpppojvdnnbomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewqnlljnkolxohushadsadafdsmmoofdslkwecfefskluhghhfddsk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlurgueeofdsororppwponzdjnkgfdgdsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkuymadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsmmoofnjlsczxfmekmfreklmfklegmkoiprewmrvlsskkkjjvvnsdnflsfpoiroppyrutrpczmc" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjvfdklmljpoplewefdswqljabpojvdnnccwcvdomwekorio" +
            "pytupewijewnrfmkslmdsdfkklrhuyiummxcvfsferjyumjhnvfdveydfguioilgfddfbbsdfferfrejymtsvxccvfsynfsnvvnreg" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlurgueeofdsororppwponzdjnkgfdgdsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkuymadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsmmoofnjlsczxfmekmfreklmfklegmkoiprewmrvlsskkkjjvvnsdnflsfpoiroppyrutrpczmc" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjvfdklmljpoplewefdswqljabpojvdnnccwcvdomwekorio" +
            "pytupewijewnrfmkslmdsdfkklrhuyiummxcvfsferjyumjhnvfdveydfguioilgfddfbbsdfferfrejymtsvxccvfsynfsnvvnreg" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpfrefeecdskjckjdsmwjklmljpoplewefdswqljdyappojvdnnccwcomwpekorio" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlljnkoltgxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpopwefrfdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlljnkolxohedushadsadafdsmmoofdslkwefsklughhhfk" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdbgfvsljpoplewewqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzbgfnljnkolxohushadsadhnhtrfbvcdafdshfdslkwecfefsklhhfk" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlugtreofdsororppwponzdjnkccadsadvfafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewvfdefdswqljdyabpppojvdnnbomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewqnlljnkolxohushadsadafdsmmoofdslkwecfefskluhghhfddsk" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmohyslkwecslkwecjdsklajbhhipoxzewddkiujynlllljnkolxohushadsadafdsmmoofdslkwefskughhhfk" +
            "lsdkckajbkakshjxjuujjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwrwjklmljpoplewefdswqljdyabpppojvdnnccwcowpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmreofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtregxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdrewbpppojvdnncwcmwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnhtwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvffvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpyrpogtdnncwcomwpekorio" +
            "lsdkckajbkakshjxzjjjgtqqbgfnhgnvkmpecdsmjkkjckjdsmwprwjklmljpoplewefdswqljdyabpppojhynnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdspoxzewqnlllljnkolxohushadsadadskljfklfdsmmoofdslkwecfefskluhghhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkccccadsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabptrojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabpppojvdnnccwcomwpekorio" +
            "eohushadsadafdsmmoofdslkwecslkwecjdsklajbhhipoxzewddqqqnlllljnkolxohushadsadafdsmmoofdslkwefsklughhhfk" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororpbgfbpwponzdjnkcadsadafdsdvsljpoplewefdswqvfvmmofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjferecdskjckjbbfgliocdsiiwjklmljpoplewefdswqljdyjabpppojvgmccwcomwekorio" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjmmnnvkmpecdskjckjdsmwprwjgrhtpopliewefdswqljdyabntppojldnnccwcowpekorio" +
            "lsdkckajbkakshjxzjjgrthyttggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabbgfpojvdnnccwmwpekorio" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnlurgueeofdsororppwponzdjnkgfdgdsadafdsdvsljpoplewefdswqvfvmmoofdslkw" +
            "jdshddsayddulksfifjejdsnfmvdkmldsnluuueeofdsororppwponzdjnkuymadsadafdsdvsljpoplewefdswqvfvmmogofdslkw" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjklmljpoplewefdswqljdyabmjhppojvnccwcomwpekorio" +
            "pytupewijewnrfmkslmdsdfkklojirejtoirejtckcretrhuyiumvlmxcvfsferjyuydfguioilfbbsdfsvxccvbnuynfsjnvvnreg" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsvmmvofnjlsczxfmekmfreklmgtrfklegmkoiprewmrvlskjjvvnsdnflsfpoiroppyrutrpczc" +
            "ecxoqwqjdasjfffksxbjnkolxohushadsadfrjjecsskkkjjvvjjjgtqqtggxfnafdsmmoofdslkwfdoinoicxzncjnkolxohusdna" +
            "ssqcdjscxfmkmtrcxzmlfnldsnhsmmoofnjlsczxfmekmfreklmfklegmkoiprewmrvlsskkkjjvvnsdnflsfpoiroppyrutrpczmc" +
            "lsdkckajbkakshjxzjjjgtqqtggxkdjvvfdvkmpecdskjckjdsmwprwjvfdklmljpoplewefdswqljabpojvdnnccwcvdomwekorio" +
            "pytupewijewnrfmkslmdsdfkklrhuyiummxcvfsferjyumjhnvfdveydfguioilgfddfbbsdfferfrejymtsvxccvfsynfsnvvnreg" +
            "blronvmfewdfnvoitrcndicoreiunclzxfpoifjflewkkjfojirejtoikcretfksxbjnkolxndoewnvrtbtpksdppoerwmpfrgtfer";

    public static void main(String[] args) {
        Instant start = Instant.now();
        ForLoopCalculator loopCalculator = new ForLoopCalculator();
        int charNumber = 26;

        int result = loopCalculator.count(str, charNumber);
        Instant end = Instant.now();
        System.out.println("耗时：" + Duration.between(start, end).toMillis() + "ms");
        System.out.println("The minimum of character appear is " + result);
    }

    @Override
    public int count(String str, int charNumber) {
        int maxNumber = Integer.MAX_VALUE;
        int[] chars = new int[charNumber];
        try {
            for (int i = 0, len = str.length(); i < len; i++) {
                char ch = str.charAt(i);
                chars[ch - 97]++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        for (int i = 0; i < charNumber; i++) {
            //System.out.println((char) (i + 97) + " appears " + chars[i] + " times! ");
            if (chars[i] < maxNumber) {
                maxNumber = chars[i];
            }
        }
        return maxNumber;
    }
}
